import jsPDF from 'jspdf';

export interface EUDRComplianceData {
  farmerId: string;
  farmerName: string;
  coordinates: string;
  riskLevel: 'low' | 'standard' | 'high';
  complianceScore: number;
  deforestationRisk: number;
  lastForestDate: string;
  documentationRequired: string[];
  recommendations: string[];
  reportId: string;
  generatedAt: string;
}

export interface DeforestationData {
  farmerId: string;
  farmerName: string;
  coordinates: string;
  forestLossDetected: boolean;
  forestLossDate: string | null;
  forestCoverChange: number;
  biodiversityImpact: 'minimal' | 'moderate' | 'significant';
  carbonStockLoss: number;
  mitigationRequired: boolean;
  recommendations: string[];
  reportId: string;
  generatedAt: string;
}

// Generate EUDR compliance PDF with LACRA letterhead
export const generateEUDRCompliancePDF = (data: EUDRComplianceData): void => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  
  // LACRA Letterhead - Green header
  pdf.setFillColor(34, 197, 94); // Green
  pdf.rect(0, 0, pageWidth, 40, 'F');
  
  // LACRA Logo area
  pdf.setFillColor(255, 255, 255);
  pdf.rect(10, 5, 35, 25, 'F');
  pdf.setDrawColor(200, 200, 200);
  pdf.rect(10, 5, 35, 25, 'S');
  
  pdf.setTextColor(0, 0, 0);
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  pdf.text('LACRA', 20, 15);
  pdf.setFontSize(6);
  pdf.text('Liberia Agriculture', 12, 20);
  pdf.text('Commodity Regulatory', 12, 23);
  pdf.text('Authority', 12, 26);
  
  // EU Compliance Badge
  pdf.setFillColor(59, 130, 246); // Blue
  pdf.rect(pageWidth - 45, 5, 35, 25, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(8);
  pdf.text('EU DEFORESTATION', pageWidth - 42, 15);
  pdf.text('REGULATION', pageWidth - 38, 19);
  pdf.text('COMPLIANT', pageWidth - 37, 23);
  
  // Main title
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text('EUDR COMPLIANCE ASSESSMENT', 55, 18);
  
  pdf.setFontSize(12);
  pdf.text('European Union Deforestation Regulation Report', 55, 28);
  
  // Report details
  let yPos = 50;
  pdf.setTextColor(0, 0, 0);
  pdf.setFontSize(10);
  pdf.text(`Report ID: ${data.reportId}`, 15, yPos);
  pdf.text(`Date: ${new Date(data.generatedAt).toLocaleDateString()}`, 15, yPos + 7);
  pdf.text(`Farmer: ${data.farmerName}`, 15, yPos + 14);
  pdf.text(`Farm ID: ${data.farmerId}`, 15, yPos + 21);
  
  // Risk Level Box
  yPos += 35;
  const riskColor = data.riskLevel === 'high' ? [220, 38, 38] : 
                    data.riskLevel === 'standard' ? [251, 191, 36] : [34, 197, 94];
  
  pdf.setFillColor(riskColor[0], riskColor[1], riskColor[2]);
  pdf.rect(10, yPos, pageWidth - 20, 15, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text(`RISK LEVEL: ${data.riskLevel.toUpperCase()}`, pageWidth / 2, yPos + 9, { align: 'center' });
  
  // Compliance Score
  yPos += 25;
  pdf.setTextColor(0, 0, 0);
  pdf.setFontSize(12);
  pdf.text('Compliance Score:', 15, yPos);
  
  // Score bar
  const scoreWidth = (data.complianceScore / 100) * 100;
  pdf.setFillColor(240, 240, 240);
  pdf.rect(15, yPos + 5, 100, 8, 'F');
  pdf.setFillColor(riskColor[0], riskColor[1], riskColor[2]);
  pdf.rect(15, yPos + 5, scoreWidth, 8, 'F');
  pdf.text(`${data.complianceScore}%`, 125, yPos + 11);
  
  // GPS Coordinates
  yPos += 25;
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('GPS Boundary Coordinates:', 15, yPos);
  
  yPos += 10;
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  const coordLines = data.coordinates.split(';');
  coordLines.forEach((coord, index) => {
    pdf.text(coord.trim(), 15, yPos + (index * 5));
  });
  
  // Recommendations
  yPos += (coordLines.length * 5) + 15;
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Recommendations:', 15, yPos);
  
  yPos += 10;
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  data.recommendations.forEach((rec, index) => {
    pdf.text(`• ${rec}`, 15, yPos + (index * 7));
  });
  
  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(100, 100, 100);
  pdf.text('This report is generated by AgriTrace360™ - LACRA Compliance System', 15, 280);
  
  // Download
  pdf.save(`EUDR_Compliance_Report_${data.farmerName.replace(/\s+/g, '_')}_${Date.now()}.pdf`);
};

// Generate deforestation analysis PDF with LACRA letterhead
export const generateDeforestationPDF = (data: DeforestationData): void => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  
  // LACRA Letterhead - Red header for deforestation
  pdf.setFillColor(220, 38, 38); // Red
  pdf.rect(0, 0, pageWidth, 40, 'F');
  
  // LACRA Logo area
  pdf.setFillColor(255, 255, 255);
  pdf.rect(10, 5, 35, 25, 'F');
  pdf.setDrawColor(200, 200, 200);
  pdf.rect(10, 5, 35, 25, 'S');
  
  pdf.setTextColor(0, 0, 0);
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  pdf.text('LACRA', 20, 15);
  pdf.setFontSize(6);
  pdf.text('Liberia Agriculture', 12, 20);
  pdf.text('Commodity Regulatory', 12, 23);
  pdf.text('Authority', 12, 26);
  
  // Environmental Badge
  pdf.setFillColor(34, 197, 94); // Green
  pdf.rect(pageWidth - 45, 5, 35, 25, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(8);
  pdf.text('ENVIRONMENTAL', pageWidth - 42, 15);
  pdf.text('MONITORING', pageWidth - 38, 19);
  pdf.text('SYSTEM', pageWidth - 35, 23);
  
  // Main title
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text('DEFORESTATION ANALYSIS', 55, 18);
  
  pdf.setFontSize(12);
  pdf.text('Environmental Impact Assessment Report', 55, 28);
  
  // Report details
  let yPos = 50;
  pdf.setTextColor(0, 0, 0);
  pdf.setFontSize(10);
  pdf.text(`Report ID: ${data.reportId}`, 15, yPos);
  pdf.text(`Date: ${new Date(data.generatedAt).toLocaleDateString()}`, 15, yPos + 7);
  pdf.text(`Property: ${data.farmerName}`, 15, yPos + 14);
  pdf.text(`Owner ID: ${data.farmerId}`, 15, yPos + 21);
  
  // Forest Loss Status
  yPos += 35;
  const statusColor = data.forestLossDetected ? [220, 38, 38] : [34, 197, 94];
  const statusText = data.forestLossDetected ? 'FOREST LOSS DETECTED' : 'NO FOREST LOSS DETECTED';
  
  pdf.setFillColor(statusColor[0], statusColor[1], statusColor[2]);
  pdf.rect(10, yPos, pageWidth - 20, 15, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text(statusText, pageWidth / 2, yPos + 9, { align: 'center' });
  
  // Environmental Metrics
  yPos += 25;
  pdf.setTextColor(0, 0, 0);
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Environmental Metrics:', 15, yPos);
  
  yPos += 15;
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  
  // Forest coverage bars
  const metrics = [
    { label: 'Forest Coverage', value: 75, color: [34, 197, 94] },
    { label: 'Agricultural Land', value: 20, color: [251, 191, 36] },
    { label: 'Cleared Areas', value: 5, color: [220, 38, 38] }
  ];
  
  metrics.forEach((metric, index) => {
    const barY = yPos + (index * 15);
    const barWidth = (metric.value / 100) * 80;
    
    pdf.text(metric.label, 15, barY + 6);
    pdf.setFillColor(240, 240, 240);
    pdf.rect(80, barY, 80, 8, 'F');
    pdf.setFillColor(metric.color[0], metric.color[1], metric.color[2]);
    pdf.rect(80, barY, barWidth, 8, 'F');
    pdf.text(`${metric.value}%`, 170, barY + 6);
  });
  
  // GPS Coordinates
  yPos += 60;
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Monitored Area Coordinates:', 15, yPos);
  
  yPos += 10;
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  const coordLines = data.coordinates.split(';');
  coordLines.forEach((coord, index) => {
    if (index < 4) { // Limit to prevent overflow
      pdf.text(coord.trim(), 15, yPos + (index * 5));
    }
  });
  
  // Recommendations
  yPos += 35;
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Environmental Recommendations:', 15, yPos);
  
  yPos += 10;
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  data.recommendations.forEach((rec, index) => {
    if (yPos < 260) { // Prevent overflow
      pdf.text(`• ${rec}`, 15, yPos + (index * 7));
    }
  });
  
  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(100, 100, 100);
  pdf.text('This report is generated by AgriTrace360™ - LACRA Environmental Monitoring System', 15, 280);
  
  // Download
  pdf.save(`Deforestation_Analysis_Report_${data.farmerName.replace(/\s+/g, '_')}_${Date.now()}.pdf`);
};